Launch script modifications were not recorded

diff --git a/itexmac2/trunk/iTM2TeXFoundation/Binaries/iTM2_Launch b/itexmac2/trunk/iTM2TeXFoundation/Binaries/iTM2_Launch
--- a/itexmac2/trunk/iTM2TeXFoundation/Binaries/iTM2_Launch
+++ b/itexmac2/trunk/iTM2TeXFoundation/Binaries/iTM2_Launch
@@ -10,7 +10,7 @@
 # this script does not care about the file extension!
 # this script should live in $iTM2_HOME/Library/TeX/bin/iTeXMac2.app/Contents/Frameworks/iTM2TeXFoundation.framework/bin/iTM2_Launch
 # The purpose is to create shortcuts to standard location where iTeXMac2 expects to find bins.
-# long names and spaces problems are solved here. Supported bin are solved too.
+# long names and spaces problems are solved here.
 #
 #iTM2_CMD_Notify comment "iTM2: STARTING $0"
 "${iTM2_TemporaryDirectory}/bin/iTeXMac2" notify echo "$(date "+START - DATE: %m/%d/%y - TIME: %H:%M:%S")"
@@ -35,53 +35,52 @@ then
 	then
 		export iTM2_PWD_Real="$(dirname "${TWSMaster}")"
 #		export iTM2_PWD="${iTM2_PWD}/Factory"
-		if [ "$iTM2_PWD_Real" == "$iTM2_PWD" ]
+		if [ "$iTM2_PWD_Real" != "$iTM2_PWD" ]
 		then
-			exit 1
-		fi
-		mkdir -p "$iTM2_PWD"
-		rm -f "$iTM2_PWD/.iTM2-src"
-		ln -s "$iTM2_PWD_Real" "$iTM2_PWD/.iTM2-src"
-		IFS="
-		"
-		pushd "$iTM2_PWD_Real" >> /dev/null
-		iTM2_PREFIX=".iTM2-src"
-		iTM2_LEVEL=1
-		while [ ${iTM2_LEVEL} -lt 5 ]
-		do
-			CANDIDATES=$(find . -maxdepth $iTM2_LEVEL -mindepth $iTM2_LEVEL -type d -not -regex ".*\.texp.*" -not -regex ".*/\..*" -print)
-			if [ ${#CANDIDATES} -eq 0 ]
-			then
-				break
-			fi
-			iTM2_PREFIX="../$iTM2_PREFIX"
+			mkdir -p "$iTM2_PWD"
+			rm -f "$iTM2_PWD/.iTM2-src"
+			ln -s "$iTM2_PWD_Real" "$iTM2_PWD/.iTM2-src"
+			IFS="
+			"
+			pushd "$iTM2_PWD_Real"
+			iTM2_PREFIX=".iTM2-src"
+			iTM2_LEVEL=1
+			while [ ${iTM2_LEVEL} -lt 5 ]
+			do
+				CANDIDATES=$(find . -maxdepth $iTM2_LEVEL -mindepth $iTM2_LEVEL -type d -not -regex ".*\.texp.*" -not -regex ".*/\..*" -print)
+				if [ ${#CANDIDATES} -eq 0 ]
+				then
+					break
+				fi
+				iTM2_PREFIX="../$iTM2_PREFIX"
+				for DIR in ${CANDIDATES}
+				do
+					mkdir -p "$iTM2_PWD/$DIR"
+					rm -f "$iTM2_PWD/$DIR/.iTM2-src"
+					ln -s "$iTM2_PREFIX/$DIR" "$iTM2_PWD/$DIR/.iTM2-src"
+				done
+				iTM2_LEVEL=$(expr $iTM2_LEVEL + 1)
+			done
+
+			CANDIDATES=$(find . -type f -not -regex ".*\.texp.*" -not -regex ".*/\..*" -print)
+			iTM2_LIMIT=10
 			for DIR in ${CANDIDATES}
 			do
-				mkdir -p "$iTM2_PWD/$DIR"
-				rm -f "$iTM2_PWD/$DIR/.iTM2-src"
-				ln -s "$iTM2_PREFIX/$DIR" "$iTM2_PWD/$DIR/.iTM2-src"
+				rm -f "$iTM2_PWD/$DIR"
+				ln -s ".iTM2-src/$(basename "$DIR")" "$iTM2_PWD/$DIR"
+				if [ ${iTM2_LIMIT} -gt 0 ]
+				then
+					break
+				else
+					iTM2_LIMIT=$(expr iTM2_LIMIT - 1)
+				fi
 			done
-			iTM2_LEVEL=$(expr $iTM2_LEVEL + 1)
-		done
+			popd
 
-		CANDIDATES=$(find . -type f -not -regex ".*\.texp.*" -not -regex ".*/\..*" -print)
-		iTM2_LIMIT=10
-		for DIR in ${CANDIDATES}
-		do
-			rm -f "$iTM2_PWD/$DIR"
-			ln -s ".iTM2-src/$(basename "$DIR")" "$iTM2_PWD/$DIR"
-			if [ ${iTM2_LIMIT} -gt 0 ]
+			if [ ${#iTM2_PWD} -gt 0 ] && ! [ -r "${iTM2_PWD}/${TWSMasterBase}" ]
 			then
-				break
-			else
-				iTM2_LIMIT=$(expr iTM2_LIMIT - 1)
+				ln -sf "{TWSMaster}" "${iTM2_PWD}"
 			fi
-		done
-		popd >> /dev/null
-
-		if [ ${#iTM2_PWD} -gt 0 ] && ! [ -r "${iTM2_PWD}/${TWSMasterBase}" ]
-		then
-			ln -sf "{TWSMaster}" "${iTM2_PWD}"
 		fi
 	fi
 else
@@ -92,7 +91,7 @@ fi
 iTM2BinaryPATH="iTM2_HOME/Library/bin"
 if [ -d "${TWSProject}" ]
 then
-	pushd "$iTM2_PWD" >> /dev/null
+	pushd "$iTM2_PWD"
 	iTM2BinaryPATH="$iTM2_PWD/.iTM2"
 	if [ ! -w "${TWSProject}" ]
 	then
@@ -258,7 +257,7 @@ do
 		"${iTM2_CMD_Notify}" notify comment "customized script ${iTM2SCRIPT}: {$(/bin/zsh -c "which ${iTM2NAME}")}"
 	fi
 done
-if [ "${iTM2_Debug}" != "0" ]
+if [ "${iTM2_Debug}:-0" != "0" ]
 then
 	"${iTM2_CMD_Notify}" notify comment "The environment is:
 $(printenv)
@@ -278,36 +277,32 @@ then
 #echo "! PATH: ${PATH}"
 #echo "the iTM2CommandPath is: ${iTM2CommandPath}"
 # This is a bug, the which command does not work and I must do the work by myself
-	if ! [ -x "${iTM2CommandPath}" ]
+	if [ -x "${iTM2CommandPath}" ]
 	then
-		iTM2WrappedCommand="${iTM2WrappedCommand#iTM2_Command_}"
-		iTM2CommandPath="$(/bin/zsh -c "which \"${iTM2WrappedCommand}\"")"
-		if ! [ -x "${iTM2CommandPath}" ]
+		if [ "${iTM2_RunSilently:-0}" == "0" ]
 		then
-			IFS="${oldIFS}"
-			"${iTM2_CMD_Notify}" notify start error
-			"${iTM2_CMD_Notify}" notify echo "No \"${iTM2Command}\" command is available neither built in nor customized"
-			"${iTM2_CMD_Notify}" notify echo "iTM2Command is \"${iTM2Command}\""
-			"${iTM2_CMD_Notify}" notify echo "iTM2IndirectCommand is \"${iTM2IndirectCommand}\""
-			"${iTM2_CMD_Notify}" notify echo "iTM2WrappedCommand is \"${iTM2WrappedCommand}\""
-			"${iTM2_CMD_Notify}" notify stop error
-			status=1
-			if [ "${iTM2_RunSilently:-0}" != "0" ]
-			then
-					"${iTM2_CMD_Notify}" notify error "the launch utility ends with $(basename "$1") Failed ($iTM2_Status)"
-			fi
-			iTeXMac2 notify echo "$(date "+END - DATE: %m/%d/%y - TIME: %H:%M:%S")"
-			exit $iTM2_Status
+				"${iTM2_CMD_Notify}" notify comment "running ${iTM2Command} (${iTM2WrappedCommand})"
 		fi
+		echo "\"${iTM2CommandPath}\"" > "${iTM2Cached}"
+		chmod u+x "${iTM2Cached}"
+		"${iTM2CommandPath}"
+		status=$?
+	else
+		IFS="${oldIFS}"
+		"${iTM2_CMD_Notify}" notify start error
+		"${iTM2_CMD_Notify}" notify echo "No \"${iTM2Command}\" command is available neither built in nor customized"
+		"${iTM2_CMD_Notify}" notify echo "iTM2Command is \"${iTM2Command}\""
+		"${iTM2_CMD_Notify}" notify echo "iTM2IndirectCommand is \"${iTM2IndirectCommand}\""
+		"${iTM2_CMD_Notify}" notify echo "iTM2WrappedCommand is \"${iTM2WrappedCommand}\""
+		"${iTM2_CMD_Notify}" notify stop error
+		status=1
+		if [ "${iTM2_RunSilently:-0}" != "0" ]
+		then
+				"${iTM2_CMD_Notify}" notify error "the launch utility ends with $(basename "$1") Failed ($iTM2_Status)"
+		fi
+		iTeXMac2 notify echo "$(date "+END - DATE: %m/%d/%y - TIME: %H:%M:%S")"
+		exit $iTM2_Status
 	fi
-	if [ "${iTM2_RunSilently:-0}" == "0" ]
-	then
-			"${iTM2_CMD_Notify}" notify comment "running ${iTM2Command} (${iTM2WrappedCommand})"
-	fi
-	echo "\"${iTM2CommandPath}\"" > "${iTM2Cached}"
-	chmod u+x "${iTM2Cached}"
-	"${iTM2CommandPath}"
-	status=$?
     if [ "${iTM2_Status}" == "0" ]
     then
         if [ "${iTM2_RunSilently:-0}" != "0" ]
