pre STABLE, the engine wrappers have been enhanced

diff --git a/itexmac2/trunk/iTM2LaTeXKit/iTM2LaTeXKitEngines/LaTeX Installer/iTM2_Engine_LaTeXInstaller b/itexmac2/trunk/iTM2LaTeXKit/iTM2LaTeXKitEngines/LaTeX Installer/iTM2_Engine_LaTeXInstaller
--- a/itexmac2/trunk/iTM2LaTeXKit/iTM2LaTeXKitEngines/LaTeX Installer/iTM2_Engine_LaTeXInstaller
+++ b/itexmac2/trunk/iTM2LaTeXKit/iTM2LaTeXKitEngines/LaTeX Installer/iTM2_Engine_LaTeXInstaller
@@ -1,41 +1,59 @@
 #!/bin/sh -f
 # this is iTM2_Engine_LaTeXInstaller wrapper
-# © 2005 jlaurens@users.sourceforge.net
+# © 2006 jlaurens@users.sourceforge.net
 iTM2_Engine_LaTeXInstaller_Version=1.0
 iTM2LaTeXInstallerEngineUsage()
 {
 iTM2_USAGE="Welcome to $(basename "$0") version ${iTM2_Engine_LaTeXInstaller_Version}
 This is iTeXMac2 built in script to wrap the LaTeX Installer engine
 ($(which "$0"))
-© 2005 jlaurens@users.sourceforge.net
+© 2006 jlaurens@users.sourceforge.net
 Usage: $(basename "$0") with environment variables
 	TWSMaster: the main input file, with an \"ins\" path extension"
 echo "$iTM2_USAGE"
-exit 0
 }
 "$iTM2_CMD_Notify" comment "Welcome to $(basename "$0") version ${iTM2_Engine_LaTeXInstaller_Version}
 This is iTeXMac2 built in script to wrap the LaTeX Installation engine
-© 2005 jlaurens@users.sourceforge.net"
+© 2006 jlaurens@users.sourceforge.net"
 iTM2_LaTeXInstaller_Engine="latex"
 iTM2_LaTeXInstaller_EnginePath="$(which "${iTM2_LaTeXInstaller_Engine}")"
 if ! [ -x "${iTM2_LaTeXInstaller_EnginePath}" ]
 then
 	"$iTM2_CMD_Notify" error "Unknown command ${iTM2_LaTeXInstaller_Engine}."
-	iTM2DVIPDFMEngineUsage
+	iTM2LaTeXInstallerEngineUsage
+	exit 1
 fi
-"$iTM2_CMD_Notify" comment "TWSMaster is: ${TWSMaster}"
-pushd "$(dirname "${TWSMaster}")"
-INPUT_DIRECTORY="${PWD}"
-INPUT="$(basename "${TWSMaster}")"
-EXTENSION="${INPUT##*.}"
+# removing the faraway project directory if any, first remove the trailing /'s
+iTM2_temp="${iTM2_Faraway_Projects_Directory}"
+iTM2_Faraway_Projects_Directory="$(echo ${iTM2_Faraway_Projects_Directory} | sed -e 's/\/$//')"
+while [ ${#iTM2_temp} -gt ${#iTM2_Faraway_Projects_Directory} ]
+do
+	iTM2_temp="${iTM2_Faraway_Projects_Directory}"
+	iTM2_Faraway_Projects_Directory="$(echo "${iTM2_Faraway_Projects_Directory}" | sed -e 's/\/$//')"
+done
+iTM2_temp="${TWSProjectDirectory#${iTM2_Faraway_Projects_Directory}}"
+if [ ${#iTM2_temp} -lt ${#TWSProjectDirectory} ]
+then
+	TWSProjectDirectory="${iTM2_temp%/*.texd}"
+fi
+"$iTM2_CMD_Notify" comment "TWSProjectDirectory is: ${TWSProjectDirectory}"
+if ! [ -d "${TWSProjectDirectory}" ]
+then
+	"$iTM2_CMD_Notify" error "Missing directory ${TWSProjectDirectory}."
+	exit 2
+fi
+pushd "${TWSProjectDirectory}"
+EXTENSION="${TWSMaster##*.}"
 EXTENSION="$(echo "${EXTENSION}" | tr 'INS' 'ins')"
 if [ "${EXTENSION}" != "ins" ]
 then
+	"$iTM2_CMD_Notify" error "Master must end with \"ins\"."
 	popd
-	exit 1
+	exit 2
 fi
-"$iTM2_CMD_Notify" comment "Performing  ${iTM2_LaTeXInstaller_EnginePath} \"${INPUT}\""
-${iTM2_LaTeXInstaller_EnginePath} "${INPUT}"
+"$iTM2_CMD_Notify" comment "Performing  ${iTM2_LaTeXInstaller_EnginePath} \"${TWSMaster}\""
+"$iTM2_CMD_Notify" comment "Current directory is: $(pwd)"
+${iTM2_LaTeXInstaller_EnginePath} "${TWSMaster}"
 popd
 if [ "${iTM2_Debug:-0}" != "0" ]
 then
diff --git a/itexmac2/trunk/iTM2TeXFoundation/Binaries/iTM2_Command_Compile b/itexmac2/trunk/iTM2TeXFoundation/Binaries/iTM2_Command_Compile
--- a/itexmac2/trunk/iTM2TeXFoundation/Binaries/iTM2_Command_Compile
+++ b/itexmac2/trunk/iTM2TeXFoundation/Binaries/iTM2_Command_Compile
@@ -1,22 +1,23 @@
 #!/bin/bash
-# this is iTM2_Command_Compile for iTeXMac2 1.4
-# © 2004 jlaurens@users.sourceforge.net
+# this is iTM2_Command_Compile for iTeXMac2
+# © 2006 jlaurens@users.sourceforge.net
 iTM2_Compile_version="1.0"
 iTM2_COMPILE_USAGE="This is iTeXMac2 compile switcher version $iTM2_Compile_version
-© 2005 jlaurens@users.sourceforge.net
-Usage: `basename "$0"` options input where options are
+© 2006 jlaurens@users.sourceforge.net
+Usage: $(basename "$0") options input where options are
        -h, --help: print this message and return.
        -m master, --master master: master is the name of the main input file.
 	   -s extension, --switch extension
        -q, --quiet: runs silently.
 Branch to the iTM2_Compile_XXX where XXX is the file extension of the given master document or when absent the switch extension.
-At least a TWSMaster shell environment variable must contain the master file name if not given through the command line."
+At least a TWSMaster shell environment variable must contain the master file name if not given through the command line.
+(TWSMaster is ${TWSMaster})"
 iTM2_Compile_RunSilently="${iTM2_RunSilently}"
 while [ $# -gt 0 ]
 do
 	case $1 in
 		-h|--help)
-			"${iTM2_CMD_Notify}" echo "$iTM2_COMPILE_USAGE"
+			"${iTM2_CMD_Notify}" echo "${iTM2_COMPILE_USAGE}"
 			exit
 		;;
 		-m|--master)
@@ -26,7 +27,7 @@ do
 							iTM2_Compile_Master="$1"
                         else
 							"${iTM2_CMD_Notify}" echo "Missing a master document"
-							"${iTM2_CMD_Notify}" echo "$iTM2_COMPILE_USAGE"
+							"${iTM2_CMD_Notify}" echo "${iTM2_COMPILE_USAGE}"
 							exit 1
                         fi
 		;;
@@ -37,7 +38,7 @@ do
 							iTM2_Compile_Switch="$1"
                         else
 							"${iTM2_CMD_Notify}" echo "Missing a switcher document"
-							"${iTM2_CMD_Notify}" echo "$iTM2_COMPILE_USAGE"
+							"${iTM2_CMD_Notify}" echo "${iTM2_COMPILE_USAGE}"
 							exit 2
                         fi
 		;;
@@ -46,30 +47,25 @@ do
 		;;
 		*)
             "${iTM2_CMD_Notify}" echo "Unknown option..."
-			"${iTM2_CMD_Notify}" echo "$iTM2_COMPILE_USAGE"
+			"${iTM2_CMD_Notify}" echo "${iTM2_COMPILE_USAGE}"
 			exit 3
 	esac
 	shift 1
 done
-if [ ${#iTM2_Compile_Master} -eq 0 ]
+if [ "${iTM2_Compile_RunSilently:-0}" == "0" ]
 then
-    iTM2_Compile_Master="${TWSMaster}"
-fi
-iTM2_Old_Master="${TWSMaster}"
-TWSMaster="${iTM2_Compile_Master}"
-if [ "${iTM2_Compile_RunSilently:-1}" -eq 0 ]
-then
-        "${iTM2_CMD_Notify}" echo "Welcome to iTeXMac2 compile switcher `basename "$0"` version $iTM2_Compile_version
+        "${iTM2_CMD_Notify}" echo "Welcome to iTeXMac2 compile switcher $(basename "$0") version ${iTM2_Compile_version}
 This is the built in shell script to compile
-© 2005 jlaurens@users.sourceforge.net
-compiling $iTM2_Compile_Master ($iTM2_Compile_Master)"
+© 2006 jlaurens@users.sourceforge.net
+compiling TWSMaster (${TWSMaster})"
 fi
-pushd "`dirname "${iTM2_Compile_Master}"`"
-iTM2_Compile_INPUT_Directory="${PWD}"
-popd
-iTM2_Compile_INPUT="$(basename "${iTM2_Compile_Master}")"
-iTM2_Compile_Extension="${iTM2_Compile_INPUT##*.}"
-iTM2_Compile_Extension="$(echo "${iTM2_Compile_Extension}" | tr 'TEX' 'tex')"
+if [ ${#iTM2_Compile_Master} -gt 0 ]
+then
+	iTM2_Old_Master="${TWSMaster}"
+	TWSMaster="${iTM2_Compile_Master}"
+fi
+iTM2_Compile_INPUT="$(basename "${TWSMaster}")"
+iTM2_Compile_Extension="$(echo "${iTM2_Compile_INPUT##*.}" | tr [:upper:] [:lower:])"
 if [ "${iTM2_Compile_Extension}" == "${iTM2_Compile_INPUT}" ]
 then
 	iTM2_Compile_Extension="${iTM2_Compile_Switch}"
@@ -77,14 +73,14 @@ then
 	then
 		"${iTM2_CMD_Notify}" error  "Missing a master file name with an extension, or an extension switcher...
 Did you give your project a master file?
-$iTM2_COMPILE_USAGE"
+${iTM2_COMPILE_USAGE}"
 		exit 5
 	fi
 fi
 iTM2_Compile_Engine="iTM2_Compile_${iTM2_Compile_Extension}"
 iTM2_Compile_Wrapped="${!iTM2_Compile_Engine}"
 # the iTM2_Compile_Engine now contains the name of the environment variable that knows the command to launch
-iTM2_Compile_EnginePath="`which "${iTM2_Compile_Wrapped}"`"
+iTM2_Compile_EnginePath="$(which "${iTM2_Compile_Wrapped}")"
 # the iTM2_Compile_EnginePath now contains the full path of the command to launch, or something weird if there is no command
 if [ ! -x "${iTM2_Compile_EnginePath}" ]
 then
@@ -114,13 +110,28 @@ then
 	done
 	IFS="$oldIFS"
 fi
-if [ ${#iTM2_Compile_EnginePath} -gt 0 ]
+if [ -x "${iTM2_Compile_EnginePath}" ]
 then
-        if [ "${iTM2_Compile_RunSilently:-1}" -eq 0 ]
+        if [ "${iTM2_Compile_RunSilently:-0}" == "0" ]
         then
 			"${iTM2_CMD_Notify}" echo "switching to ${iTM2_Compile_EnginePath}"
         fi
         "${iTM2_Compile_EnginePath}"
+		iTM2_Status=$?
+		if [ ${#iTM2_Old_Master} -gt 0 ]
+		then
+			TWSMaster="${iTM2_Old_Master}"
+		fi
+		if [ "${iTM2_Status}" != "0" ]
+		then
+				"${iTM2_CMD_Notify}" error "The built in compile switcher ends with $(basename "$0") FAILED(${iTM2_Status})"
+				exit ${iTM2_Status}
+		elif [ "${iTM2_Compile_RunSilently:-0}" == "0" ]
+		then
+				"${iTM2_CMD_Notify}" echo "The built in compile switcher ends with $(basename "$0") complete"
+				exit 0
+		fi
+		
 else
 		"${iTM2_CMD_Notify}" error "Could not manage the extension ${iTM2_Compile_Extension}, no switcher found."
 		"${iTM2_CMD_Notify}" error "Go to the project settings panel, select advanced settings and the compile tab view."
@@ -138,9 +149,3 @@ else
 		done
 		exit 1
 fi
-TWSMaster="${iTM2_Old_Master}"
-if [ "${iTM2_Compile_RunSilently:-1}" -eq 0 ]
-then
-        "${iTM2_CMD_Notify}" echo "The built in compile switcher ends with `basename "$0"` complete"
-fi
-exit 0
diff --git a/itexmac2/trunk/iTM2TeXFoundation/Binaries/iTM2_Launch b/itexmac2/trunk/iTM2TeXFoundation/Binaries/iTM2_Launch
--- a/itexmac2/trunk/iTM2TeXFoundation/Binaries/iTM2_Launch
+++ b/itexmac2/trunk/iTM2TeXFoundation/Binaries/iTM2_Launch
@@ -19,15 +19,16 @@ then
     iTM2_Device="/dev/null"
 fi
 iTM2Command="$1"
+# Sanity check: TWSMaster must be a readable file, no condition on TWSFront, TWSProject, TWSWrapper
+
 iTM2BinaryPATH=""
-iTM2PROJECT="$TWSProjectDirectory/$TWSProjectName"
-if [ -d "${iTM2PROJECT}" ]
+if [ -d "${TWSProject}" ]
 then
-	pushd "`dirname "${iTM2PROJECT}"`"
-	iTM2BinaryPATH="`pwd`/`basename "${iTM2PROJECT}"`/.iTM2"
-	if [ ! -w "${iTM2PROJECT}" ]
+	pushd "$(dirname "${TWSProject}")"
+	iTM2BinaryPATH="$(basename "${TWSProject}")/.iTM2"
+	if [ ! -w "${TWSProject}" ]
 	then
-		"${iTM2_CMD_Notify}" error "Project MUST BE writable (${iTM2PROJECT})"
+		"${iTM2_CMD_Notify}" error "Project MUST BE writable (${TWSProject})"
 		exit -1
 	fi
 	if [ "${iTM2_XLR8:-0}" == "0" ] || [ ! -d "${iTM2BinaryPATH}" ]
@@ -44,19 +45,19 @@ then
 		chmod -R a+rwx "${iTM2BinaryPATH}"
 	fi
 else
-    "${iTM2_CMD_Notify}" warning "Undefined project in $0, using the invisible folder named $PWD/.iTM2"
-	iTM2PROJECT=""
+    "${iTM2_CMD_Notify}" warning "Undefined project in $0, using the invisible folder named ${TWSMaster}/.iTM2"
+	TWSProject=""# project is neutralized
 	iTM2BinaryPATH=".iTM2"
 	rm -Rf "${iTM2BinaryPATH}"
 	mkdir "${iTM2BinaryPATH}"
-	chmod -R a+rwx "${iTM2BinaryPATH}"
+	chmod -R u+rwx "${iTM2BinaryPATH}"
 fi
-date "+MIDDLE - DATE(4): %m/%d/%y%nTIME: %H:%M:%S"
+#date "+MIDDLE - DATE(4): %m/%d/%y%nTIME: %H:%M:%S"
 iTM2Cached="${iTM2BinaryPATH}/${iTM2Command}-cached"
 if [ "${iTM2_XLR8:-0}" != "0" ] && [ 0 -eq 1 ]
 then
 	"${iTM2_CMD_Notify}" echo "<second time/>"
-date "+SECOND - DATE: %m/%d/%y%nTIME: %H:%M:%S"
+#date "+SECOND - DATE: %m/%d/%y%nTIME: %H:%M:%S"
 	if [ -x "${iTM2Cached}" ]
 	then
 		"${iTM2_CMD_Notify}" echo "<iTM2TaskStarted/>"
@@ -68,36 +69,36 @@ date "+SECOND - DATE: %m/%d/%y%nTIME: %H:%M:%S"
 	fi
 else
 	"${iTM2_CMD_Notify}" echo "<first time/>"
-date "+FIRST - DATE: %m/%d/%y%nTIME: %H:%M:%S"
+#date "+FIRST - DATE: %m/%d/%y%nTIME: %H:%M:%S"
 fi
-date "+MIDDLE - DATE(3.1): %m/%d/%y%nTIME: %H:%M:%S"
+#date "+MIDDLE - DATE(3.1): %m/%d/%y%nTIME: %H:%M:%S"
 "${iTM2_CMD_Notify}" echo "<iTM2TaskStarted/>"
-date "+MIDDLE - DATE(3.0): %m/%d/%y%nTIME: %H:%M:%S"
+#date "+MIDDLE - DATE(3.0): %m/%d/%y%nTIME: %H:%M:%S"
 iTM2SHORT="0"
 iTM2Link ()
 {
 	iTM2_TARGET="${iTM2BinaryPATH}/$iTM2SHORT"
-    rm -Rf "$iTM2_TARGET"
+    rm -Rf "${iTM2_TARGET}"
     if ( [ -d "$1" ] ) && ( [ -d "$1/bin" ] )
     then
 		ln -s "$1" "${iTM2_TARGET}"
-		iTM2PREFIX="$iTM2PREFIX:$iTM2_TARGET/bin";
-		iTM2SHORT=`expr $iTM2SHORT + 1`
+		iTM2PREFIX="${iTM2PREFIX}:${iTM2_TARGET}/bin";
+		iTM2SHORT=$(expr ${iTM2SHORT} + 1)
     fi
 }
-date "+MIDDLE - DATE(2): %m/%d/%y%nTIME: %H:%M:%S"
+#date "+MIDDLE - DATE(2): %m/%d/%y%nTIME: %H:%M:%S"
 "${iTM2_CMD_Notify}" comment "Welcome to iTeXMac2 launch utility version ${iTM2_LAUNCH_VERSION}"
 date "+MIDDLE - DATE(1): %m/%d/%y%nTIME: %H:%M:%S"
-if [ "${TWSMaster}" == "" ]
+if [ ${#TWSMaster} -eq 0 ]
 then
     "${iTM2_CMD_Notify}" error "Undefined TWSMaster in $0
 You MUST specify a master document, from the project settings panel
 Here are the environment variables
-`printenv`
+$(printenv)
 Are they what was expected?"
     exit 1
 fi
-# the specific environment:
+# the specific environment: (this is time consuming when debugging)
 date "+MIDDLE - DATE(0): %m/%d/%y%nTIME: %H:%M:%S"
 if [ ${#iTM2_Debug} -gt 0 ]
 then
@@ -111,17 +112,6 @@ then
 fi
 date "+MIDDLE - DATE: %m/%d/%y%nTIME: %H:%M:%S"
 # the binary path:
-if ! [ -d "${TWSProjectDirectory}" ]
-then
-	"${iTM2_CMD_Notify}" error "Missing directory at path: {${iTM2ProjectDirectory}}, do not expect a correct behaviour."
-fi
-if [ ! -w "${PWD}" ]
-then
-	"${iTM2_CMD_Notify}" error "Current folder is not writable:
-$PWD,
-copy your source in a writable location"
-	exit -1
-fi
 iTM2PREFIX=".:${iTM2BinaryPATH}"
 iTM2SHORT="0"
 iTM2Link "${iTM2_HOME}/Library/TeX"
@@ -137,8 +127,8 @@ then
 	iTM2Link "/Network/Library/TeX"
 	iTM2Link "/Network/Library/Application Support/iTeXMac2"
 fi
-iTM2_BUILTIN_EXECUTABLE_PATH="`dirname "$0"`"
-iTM2Link "`dirname "$iTM2_BUILTIN_EXECUTABLE_PATH"`"
+iTM2_BUILTIN_EXECUTABLE_PATH="$(dirname "$0")"
+iTM2Link "$(dirname "$iTM2_BUILTIN_EXECUTABLE_PATH")"
 # Now we are setting the PATH variable
 if [ ${#iTM2PREFIX} -gt 0 ]
 then
@@ -157,15 +147,15 @@ do
 	eval "${iTM2SCRIPT}=\"customized\""
 	if [ ${#iTM2_Debug} -gt 0 ]
 	then
-		"${iTM2_CMD_Notify}" comment "customized script ${iTM2SCRIPT}: {`which ${iTM2NAME}`}"
+		"${iTM2_CMD_Notify}" comment "customized script ${iTM2SCRIPT}: {$(which ${iTM2NAME})}"
 	fi
 done
 if [ ${#iTM2_Debug} -gt 0 ]
 then
 	"${iTM2_CMD_Notify}" comment "The environment is:
-`printenv`
+$(printenv)
 The binaries are (${iTM2BinaryPATH}):
-`ls -al "${iTM2BinaryPATH}"`"
+$(ls -al "${iTM2BinaryPATH}")"
 fi
 #"${iTM2_CMD_Notify}" comment "##### DIAGNOSTIC"
 #printenv
@@ -177,8 +167,12 @@ if [ $# -gt 0 ]
 then
     iTM2IndirectCommand="iTM2_${iTM2Command}"
     iTM2WrappedCommand="${!iTM2IndirectCommand}"
-    iTM2CommandPath="`which "${iTM2WrappedCommand}"`"
+#echo "! iTM2WrappedCommand: ${iTM2WrappedCommand}"
+    iTM2CommandPath="$(which "${iTM2WrappedCommand}")"
+#echo "! iTM2CommandPath: ${iTM2CommandPath}"
+#echo "! PATH: ${PATH}"
 #echo "the iTM2CommandPath is: ${iTM2CommandPath}"
+# This is a bug, the which command does not work and I must do the work by myself
     if [ ! -x "${iTM2CommandPath}" ]
 	then
 #echo "iTM2Command is: $iTM2Command"
@@ -200,9 +194,9 @@ then
 			fi
 		done
 	fi
-	if [ ${#iTM2CommandPath} -gt 0 ]
+	if [ -x "${iTM2CommandPath}" ]
 	then
-		if [ ${#iTM2_RunSilently} -eq 0 ]
+		if [ "${iTM2_RunSilently:-0}" == "0" ]
 		then
 				"${iTM2_CMD_Notify}" comment "running ${iTM2Command} (${iTM2WrappedCommand})"
 		fi
@@ -218,27 +212,27 @@ then
 		"${iTM2_CMD_Notify}" echo "iTM2IndirectCommand is \"${iTM2IndirectCommand}\""
 		"${iTM2_CMD_Notify}" echo "iTM2WrappedCommand is \"${iTM2WrappedCommand}\""
 		"${iTM2_CMD_Notify}" stop error
-		status="1"
-		if [ ${#iTM2_RunSilently} -gt 0 ]
+		status=1
+		if [ "${iTM2_RunSilently:-0}" != "0" ]
 		then
-				"${iTM2_CMD_Notify}" error "the launch utility ends with `basename "$1"` Failed ($status)"
+				"${iTM2_CMD_Notify}" error "the launch utility ends with $(basename "$1") Failed ($iTM2_Status)"
 		fi
-		exit 1
+		exit $iTM2_Status
 	fi
 date "+END - DATE: %m/%d/%y%nTIME: %H:%M:%S"
-    if [ "$status" = "0" ]
+    if [ "${iTM2_Status}" == "0" ]
     then
-        if [ ${#iTM2_RunSilently} -eq 0 ]
+        if [ "${iTM2_RunSilently:-0}" != "0" ]
         then
-                "${iTM2_CMD_Notify}" comment "the launch utility ends with `basename "$1"` Complete"
+                "${iTM2_CMD_Notify}" comment "the launch utility ends with $(basename "$1") Complete"
         fi
         exit 0
     else
-        if [ ${#iTM2_RunSilently} -eq 0 ]
+        if [ "${iTM2_RunSilently:-0}" != "0" ]
         then
-                "${iTM2_CMD_Notify}" error "the launch utility ends with `basename "$1"` Failed ($status)"
+                "${iTM2_CMD_Notify}" error "the launch utility ends with $(basename "$1") Failed ($iTM2_Status)"
         fi
-        exit 1
+        exit $iTM2_Status
     fi
 else
 	exit 2
diff --git a/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/TeX/iTM2_Engine_PDFTeX b/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/TeX/iTM2_Engine_PDFTeX
--- a/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/TeX/iTM2_Engine_PDFTeX
+++ b/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/TeX/iTM2_Engine_PDFTeX
@@ -1,61 +1,63 @@
 #!/bin/sh -f
 # this is iTM2_Engine_PDFTeX for iTeXMac2 2.0
-# © 2005 jlaurens@users.sourceforge.net
+# © 2006 jlaurens AT users DOT sourceforge DOT net
 # This is a pdfeTeX 3.141592-1.20a-2.2 (Web2C 7.5.3) wrapper
 iTM2_PDFTeX_Engine_Version=1.0
 iTM2PDFTeXEngineUsage()
 {
-iTM2_USAGE="Welcome to `basename "$0"` version ${iTM2_PDFTeX_Engine_Version}
+iTM2_Usage="Welcome to $(basename "$0") version ${iTM2_PDFTeX_Engine_Version}
 This is iTeXMac2 built in script to wrap the pdftex engine
-(`which "$0"`)
-© 2005 jlaurens@users.sourceforge.net
-Usage: `basename "$0"` with environment variables
-	TWSMaster: the main input file
-	iTM2_Continuous_Compile: 1 or 0
-	iTM2_USE_output_directory: 1 or 0 (common)
+($(which pdftex))
+© 2006 jlaurens@users.sourceforge.net
+Usage: $(basename "$0") with environment variables
+	TWSMaster: the main input file (actually \"${TWSMaster}\")
+	TWSProject: the project file, if any, full path, unused
+	TWSWrapper: the wrapper file, if any, full path, unused
+	iTM2_Continuous_Compile: 1 or void
+	iTM2_USE_output_directory: 1 or void (common)
 	iTM2_output_directory: the common output directory
-	iTM2_PDFTeX_ini: 1 or 0, be initex, for dumping formats
-	iTM2_PDFTeX_mltex: 1 or 0, enable MLTeX extensions such as \charsubdef
-	iTM2_PDFTeX_enc: 1 or 0,
+	iTM2_PDFTeX_ini: 1 or void, be initex, for dumping formats
+	iTM2_PDFTeX_mltex: 1 or void, enable MLTeX extensions such as \charsubdef
+	iTM2_PDFTeX_enc: 1 or void,
 	iTM2_PDFTeX_MoreArgument:
-	iTM2_PDFTeX_mktex: 1 or 0,
-	iTM2_PDFTeX_USE_output_directory: 1 or 0
+	iTM2_PDFTeX_mktex: 1 or void,
+	iTM2_PDFTeX_USE_output_directory: 1 or void
 	iTM2_PDFTeX_output_directory:
 	iTM2_PDFTeX_output_format: \"pdf\" or \"dvi\"
 	iTM2_PDFTeX_fmt: = FMTNAME, use the value instead of program name or a %& line
-	iTM2_PDFTeX_parse_first_line: 1 or 0, parse of the first line of the input file
-	iTM2_PDFTeX_USE_progname: 1 or 0,
+	iTM2_PDFTeX_parse_first_line: 1 or void, parse of the first line of the input file
+	iTM2_PDFTeX_USE_progname: 1 or void,
 	iTM2_PDFTeX_progname: = STRING, set program (and fmt) name to STRING
-	iTM2_PDFTeX_USE_jobname: 1 or 0,
+	iTM2_PDFTeX_USE_jobname: 1 or void,
 	iTM2_PDFTeX_jobname: = STRING, set the job name to STRING
-	iTM2_PDFTeX_shell_escape: 1 or 0, enable \write18{SHELL COMMAND}
-	iTM2_PDFTeX_PDFSYNC: 1 or 0,
-	iTM2_PDFTeX_src_specials: 1 or 0, insert source specials into the DVI file
-	iTM2_PDFTeX_src_specials_where_no_cr: 1 or 0,
-	iTM2_PDFTeX_src_specials_where_no_display: 1 or 0,
-	iTM2_PDFTeX_src_specials_where_no_hbox: 1 or 0,
-	iTM2_PDFTeX_src_specials_where_no_parent: 1 or 0,
-	iTM2_PDFTeX_src_specials_where_no_par: 1 or 0,
-	iTM2_PDFTeX_src_specials_where_no_math: 1 or 0,
-	iTM2_PDFTeX_src_specials_where_no_vbox: 1 or 0,
-	iTM2_PDFTeX_USE_output_comment: 1 or 0,
+	iTM2_PDFTeX_shell_escape: 1 or void, enable \write18{SHELL COMMAND}
+	iTM2_PDFTeX_PDFSYNC: 1 or void,
+	iTM2_PDFTeX_src_specials: 1 or void, insert source specials into the DVI file
+	iTM2_PDFTeX_src_specials_where_no_cr: 1 or void,
+	iTM2_PDFTeX_src_specials_where_no_display: 1 or void,
+	iTM2_PDFTeX_src_specials_where_no_hbox: 1 or void,
+	iTM2_PDFTeX_src_specials_where_no_parent: 1 or void,
+	iTM2_PDFTeX_src_specials_where_no_par: 1 or void,
+	iTM2_PDFTeX_src_specials_where_no_math: 1 or void,
+	iTM2_PDFTeX_src_specials_where_no_vbox: 1 or void,
+	iTM2_PDFTeX_USE_output_comment: 1 or void,
 	iTM2_PDFTeX_output_comment:
-	iTM2_PDFTeX_USE_translate_file: 1 or 0,
-	iTM2_PDFTeX_translate_file := TCXNAME, use the TCX file TCXNAME
-	iTM2_PDFTeX_PARSE_translate_file: 1 or 0,
-	iTM2_PDFTeX_recorder: 1 or 0, enable filename recorder
-	iTM2_PDFTeX_file_line_error: 1 or 0, print file:line:error style messages
-	iTM2_PDFTeX_halt_on_error: 1 or 0,
+	iTM2_PDFTeX_USE_translate_file: 1 or void,
+	iTM2_PDFTeX_translate_file : = TCXNAME, use the TCX file TCXNAME
+	iTM2_PDFTeX_PARSE_translate_file: 1 or void,
+	iTM2_PDFTeX_recorder: 1 or void, enable filename recorder
+	iTM2_PDFTeX_file_line_error: 1 or void, print file:line:error style messages
+	iTM2_PDFTeX_halt_on_error: 1 or void,
 	iTM2_PDFTeX_interaction: batchmode/nonstopmode/scrollmode/errorstopmode, set interaction mode
-	iTM2_PDFTeX_kpathsea_debug:
+	iTM2_PDFTeX_kpathsea_debug: 1 or void
 	iTM2_PDFTeX_MoreArgument: more arguments"
-echo "$iTM2_USAGE"
-exit 0
+	echo "$iTM2_Usage"
 }
-"$iTM2_CMD_Notify" comment "Welcome to `basename "$0"` version ${iTM2_PDFTeX_Engine_Version}
-This is iTeXMac2 built in script to wrap the pdftex engine
-© 2005 jlaurens@users.sourceforge.net"
-if [ "${iTM2_Debug:-0}" != "0" ]
+"$iTM2_CMD_Notify" comment "Welcome to $(basename "$0") version ${iTM2_PDFTeX_Engine_Version}
+This is iTeXMac2 built in script to wrap the pdftex engine at
+$(which pdftex)
+© 2006 jlaurens@users.sourceforge.net"
+if [ ${#iTM2_Debug} -gt 0 ]
 then
 	"$iTM2_CMD_Notify" start comment
 	"$iTM2_CMD_Notify" echo "The $0 specific environment is:"
@@ -65,42 +67,16 @@ then
 	done
 	"$iTM2_CMD_Notify" stop comment
 fi
-
+# the engine part
 iTM2_PDFTeX_Engine="pdftex"
-iTM2_PDFTeX_EnginePath="`which "${iTM2_PDFTeX_Engine}"`"
+iTM2_PDFTeX_EnginePath="$(which "${iTM2_PDFTeX_Engine}")"
 if ! [ -x "${iTM2_PDFTeX_EnginePath}" ]
 then
 	"$iTM2_CMD_Notify" error "Unknown command ${iTM2_PDFTeX_Engine}."
 	iTM2PDFTeXEngineUsage
+	exit 1
 fi
-EXTENSION="$(basename ${TWSMaster})"
-EXTENSION="${EXTENSION##*.}"
-if [ ${#EXTENSION} -ne 0 ]
-then
-	EXTENSION="$(echo "${EXTENSION}" | tr 'TEX' 'tex')"
-	if [ "${EXTENSION}" != "tex" ]
-	then
-		TWSMaster="${TWSMaster%.*}.tex"
-	fi
-fi
-if ! [ -r "${TWSMaster}" ]
-then
-	"$iTM2_CMD_Notify" error "No readable file at ${TWSMaster} (in $(pwd) / ${PWD})."
-	iTM2PDFTeXEngineUsage
-fi
-"$iTM2_CMD_Notify" comment "TWSMaster is: ${TWSMaster}"
-pushd "$(dirname "${TWSMaster}")"
-INPUT_DIRECTORY="${PWD}"
-popd
-INPUT="$(basename "${TWSMaster}")"
 iTM2_PDFTeX_Arguments=""
-if [ "${iTM2_PDFTeX_USE_jobname:-0}" != "0" ] && [ ${#iTM2_PDFTeX_jobname} -ne 0 ]
-then
-	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -jobname \"${iTM2_PDFTeX_jobname}\""
-	OUTPUT="${iTM2_PDFTeX_jobname}"
-else
-	OUTPUT="${INPUT%.*}"
-fi
 if [ "${iTM2_PDFTeX_ini:-0}" != "0" ]
 then
 	iTM2_PDFTeX_Arguments="-ini"
@@ -121,7 +97,7 @@ then
 else
 	if [ "${iTM2_PDFTeX_output_format:-pdf}" == "dvi" ]
 	then
-		iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -output-format ${iTM2_PDFTeX_output_format}"
+		iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -output-format ${iTM2_PDFTeX_output_format:-pdf}"
 		if [ "${iTM2_PDFTeX_USE_output_comment:-0}" != "0" ] && [ ${#iTM2_PDFTeX_output_comment} -ne 0 ]
 		then
 			iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -output-comment \"${iTM2_PDFTeX_output_comment}\""
@@ -183,15 +159,15 @@ else
 					iTM2_SRC_SPECIALS="vbox"
 				fi
 			fi
-			if [ "${iTM2_PDFTeX_src_specials_no_parent:-0}" == "0" ]
-			then
-				if [ ${#iTM2_SRC_SPECIALS} -gt 0 ]
-				then
-					iTM2_SRC_SPECIALS="${iTM2_SRC_SPECIALS},parent"
-				else
-					iTM2_SRC_SPECIALS="parent"
-				fi
-			fi
+#			if [ "${iTM2_PDFTeX_src_specials_no_parent:-0}" == "0" ]
+#			then
+#				if [ ${#iTM2_SRC_SPECIALS} -gt 0 ]
+#				then
+#					iTM2_SRC_SPECIALS="${iTM2_SRC_SPECIALS},parent"
+#				else
+#					iTM2_SRC_SPECIALS="parent"
+#				fi
+#			fi
 			if [ ${#iTM2_SRC_SPECIALS} -gt 0 ]
 			then
 				iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -src-specials=${iTM2_SRC_SPECIALS}"
@@ -210,11 +186,11 @@ fi
 if [ "${iTM2_PDFTeX_USE_output_directory:-0}" != "0" ] && [ ${#iTM2_PDFTeX_output_directory} -ne 0 ]
 then
 	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -output-directory \"${iTM2_PDFTeX_output_directory}\""
-elif [ "${iTM2_PDFTeX_USE_output_directory:-0}" != "0" ] && [ ${#iTM2_PDFTeX_output_directory} -ne 0 ]
+elif [ "${iTM2_USE_output_directory:-0}" != "0" ] && [ ${#iTM2_output_directory} -ne 0 ]
 then
-	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -output-directory \"${iTM2_PDFTeX_output_directory}\""
+	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -output-directory \"${iTM2_output_directory}\""
 fi
-iTM2_PDFTeX_fmt="`echo ${iTM2_PDFTeX_fmt} | tr [:upper:] [:lower:]`"
+iTM2_PDFTeX_fmt="$(echo ${iTM2_PDFTeX_fmt} | tr [:upper:] [:lower:])"
 if [ "${iTM2_PDFTeX_parse_first_line:-0}" != "0" ]
 then
 	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -parse-first-line"
@@ -290,27 +266,92 @@ if [ "${iTM2_PDFTeX_kpathsea_debug:-0}" != "0" ]
 then
 	"$iTM2_CMD_Notify" error "-kpathsea-debug no yet supported."
 fi
-if [ ${#iTM2_PDFTeX_interaction} -gt 0 ] && [ "${iTM2_ContinuousCompile:-0}" == "0" ]
+if [ "${iTM2_PDFTeX_interaction:-0}" != "0" ] && [ "${iTM2_ContinuousCompile:-0}" == "0" ]
 then
 	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -interaction ${iTM2_PDFTeX_interaction}"
 fi
 if [ "${iTM2_PDFTeX_USE_MoreArgument:-0}" != "0" ] && [ ${#iTM2_PDFTeX_MoreArgument} -ne 0 ]
 then
-	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} \"${iTM2_PDFTeX_MoreArgument}\""
+	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} ${iTM2_PDFTeX_MoreArgument}"
 fi
-pushd "${INPUT_DIRECTORY}"
-"$iTM2_CMD_Notify" comment "Performing  ${iTM2_PDFTeX_EnginePath} ${iTM2_PDFTeX_Arguments} \"${INPUT}\""
-${iTM2_PDFTeX_EnginePath} ${iTM2_PDFTeX_Arguments} "${INPUT}"
-popd
+# the file name part
+EXTENSION="$(basename ${TWSMaster})"
+EXTENSION="${EXTENSION##*.}"
+if [ ${#EXTENSION} -ne 0 ]
+then
+	EXTENSION="$(echo "${EXTENSION}" | tr [:upper:] [:lower:])"
+	if [ "${EXTENSION}" != "tex" ] && [ "${EXTENSION}" != "dtx" ] && [ "${EXTENSION}" != "ins" ] && [ "${EXTENSION}" != "ltx" ]
+	then
+		TWSMaster="${TWSMaster%.*}.tex"
+	fi
+fi
+if ! [ -r "${TWSMaster}" ]
+then
+	"$iTM2_CMD_Notify" error "No readable file at ${TWSMaster} (in $(pwd))."
+	iTM2PDFTeXEngineUsage
+	exit 2
+fi
+"$iTM2_CMD_Notify" comment "TWSMaster is: ${TWSMaster}"
+TWSMasterBase="$(basename "${TWSMaster}")"
+if [ "${iTM2_PDFTeX_USE_jobname:-0}" != "0" ] && [ ${#iTM2_PDFTeX_jobname} -ne 0 ]
+then
+	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -jobname \"${iTM2_PDFTeX_jobname}\""
+	OUTPUT="${iTM2_PDFTeX_jobname}"
+else
+	OUTPUT="${TWSMasterBase%.*}"
+fi
+# working directory?
+if [ ${#TWSProject} -gt 0 ]
+then
+	iTM2_PWD="$(dirname "${TWSProject}")"
+	iTM2_PWD_Real="${iTM2_PWD##*Projects.put_aside}"
+	iTM2_PWD_Real="${iTM2_PWD_Real%/*.texd*}"
+	if [ ${#iTM2_PWD_Real} -lt ${#iTM2_PWD} ]
+	then
+		if [ ${#TEXINPUTS} -gt 0 ]
+		then
+			export TEXINPUTS=".:${iTM2_PWD_Real}:${TEXINPUTS}:"
+		else
+			export TEXINPUTS=".:${iTM2_PWD_Real}:"
+		fi
+		if [ ${#iTM2_PWD} -gt 0 ] && ! [ -r "${iTM2_PWD}/${TWSMasterBase}" ]
+		then
+			ln -sf "{TWSMaster}" "${iTM2_PWD}"
+		fi
+	fi
+else
+	iTM2_PWD="$(dirname "${TWSMaster}")"
+	iTM2_PWD_Real="${iTM2_PWD}"
+fi
+pushd "${iTM2_PWD}"
+"$iTM2_CMD_Notify" comment "Performing  ${iTM2_PDFTeX_EnginePath} ${iTM2_PDFTeX_Arguments} \"${TWSMasterBase}\""
+"${iTM2_PDFTeX_EnginePath}" ${iTM2_PDFTeX_Arguments} "${TWSMasterBase}"
+iTM2_Status="$?"
+if [ "${iTM2_Status}" != "0" ]
+then
+	popd
+	"$iTM2_CMD_Notify" error "$0 FAILED(${iTM2_Status})."
+	exit ${iTM2_Status}
+fi
 if [ "${iTM2_PDFTeX_output_format:-pdf}" == "dvi" ] # no external viewer supported...
 then
-	"$iTM2_CMD_Notify" comment "Swicthing to a dvi to ps filter for ${INPUT_DIRECTORY}/${OUTPUT%.*}"
-	iTM2_Command_Compile --master "${INPUT_DIRECTORY}/${OUTPUT%.*}" --switch dvi
-else
-	"${iTM2_TemporaryDirectory}/bin/iTeXMac2" update -file "${INPUT_DIRECTORY}/${OUTPUT%.*}.pdf" -project "${TWSProjectDirectory}/${TWSProjectName}"
+	"$iTM2_CMD_Notify" comment "Swicthing to a dvi to ps filter for ${iTM2_PWD}/${OUTPUT%.*}"
+	iTM2_Command_Compile --master "${iTM2_PWD}/${OUTPUT%.*}" --switch dvi
 fi
-if [ "${iTM2_Debug:-0}" != "0" ]
+OUTPUT="${OUTPUT%.*}.pdf"
+if [ -s "${OUTPUT}" ]
+then	
+	if [ ${#iTM2_PWD_Real} -lt ${#iTM2_PWD} ] && [ -w "${iTM2_PWD_Real}" ]
+	then
+		mv -f "${OUTPUT}" "${iTM2_PWD_Real}"
+	fi
+	"${iTM2_TemporaryDirectory}/bin/iTeXMac2" update -file "${iTM2_PWD_Real}/${OUTPUT}" -project "${TWSProject}"
+else
+	"${iTM2_TemporaryDirectory}/bin/iTeXMac2" markerror -file "${iTM2_PWD_Real}/${OUTPUT}" -project "${TWSProject}"
+fi
+if [ ${#iTM2_Debug} -gt 0 ]
 then
 	"$iTM2_CMD_Notify" comment "$0 complete."
 fi
+popd
 exit 0
diff --git a/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/TeX/iTM2_Engine_TeX b/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/TeX/iTM2_Engine_TeX
--- a/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/TeX/iTM2_Engine_TeX
+++ b/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/TeX/iTM2_Engine_TeX
@@ -1,58 +1,59 @@
 #!/bin/sh -f
 # this is iTM2_Engine_TeX for iTeXMac2 2.0
-# © 2004 jlaurens@users.sourceforge.net
+# © 2006 jlaurens AT users DOT sourceforge DOT net
 # This is a TeX 3.141592 (Web2C 7.5.3) wrapper
 iTM2_TeX_Engine_Version=1.0
 iTM2TeXEngineUsage()
 {
 iTM2_USAGE="Welcome to $(basename "$0") version ${iTM2_TeX_Engine_Version}
 This is iTeXMac2 built in script to wrap the tex engine
-($(which "$0"))
-© 2005 jlaurens@users.sourceforge.net
+($(which tex))
+© 2006 jlaurens@users.sourceforge.net
 Usage: $(basename "$0") with environment variables
-	TWSMaster: the main input file
-	iTM2_USE_output_directory: 1 or 0 (common)
+	TWSMaster: the main input file (actually \"${TWSMaster}\")
+	TWSProject: the project file, if any, full path, unused
+	TWSWrapper: the wrapper file, if any, full path, unused
+	iTM2_USE_output_directory: 1 or void (common)
 	iTM2_output_directory: the common output directory
-	iTM2_TeX_ini: 1 or 0, be initex, for dumping formats
-	iTM2_TeX_mltex: 1 or 0, enable MLTeX extensions such as \charsubdef
-	iTM2_TeX_enc: 1 or 0,
+	iTM2_TeX_ini: 1 or void, be initex, for dumping formats
+	iTM2_TeX_mltex: 1 or void, enable MLTeX extensions such as \charsubdef
+	iTM2_TeX_enc: 1 or void,
 	iTM2_TeX_MoreArgument:
-	iTM2_TeX_mktex: 1 or 0,
-	iTM2_TeX_USE_output_directory: 1 or 0
+	iTM2_TeX_mktex: 1 or void,
+	iTM2_TeX_USE_output_directory: 1 or void
 	iTM2_TeX_output_directory:
 	iTM2_TeX_fmt: = FMTNAME, use the value instead of program name or a %& line
-	iTM2_TeX_parse_first_line: 1 or 0, parse of the first line of the input file
-	iTM2_TeX_USE_progname: 1 or 0,
+	iTM2_TeX_parse_first_line: 1 or void, parse of the first line of the input file
+	iTM2_TeX_USE_progname: 1 or void,
 	iTM2_TeX_progname: = STRING, set program (and fmt) name to STRING
-	iTM2_TeX_USE_jobname: 1 or 0,
+	iTM2_TeX_USE_jobname: 1 or void,
 	iTM2_TeX_jobname: = STRING, set the job name to STRING
-	iTM2_TeX_shell_escape: 1 or 0, enable \write18{SHELL COMMAND}
-	iTM2_TeX_src_specials: 1 or 0, insert source specials into the DVI file
-	iTM2_TeX_src_specials_where_no_cr: 1 or 0,
-	iTM2_TeX_src_specials_where_no_display: 1 or 0,
-	iTM2_TeX_src_specials_where_no_hbox: 1 or 0,
-	iTM2_TeX_src_specials_where_no_parent: 1 or 0,
-	iTM2_TeX_src_specials_where_no_par: 1 or 0,
-	iTM2_TeX_src_specials_where_no_math: 1 or 0,
-	iTM2_TeX_src_specials_where_no_vbox: 1 or 0,
-	iTM2_TeX_USE_output_comment: 1 or 0,
+	iTM2_TeX_shell_escape: 1 or void, enable \write18{SHELL COMMAND}
+	iTM2_TeX_src_specials: 1 or void, insert source specials into the DVI file
+	iTM2_TeX_src_specials_where_no_cr: 1 or void,
+	iTM2_TeX_src_specials_where_no_display: 1 or void,
+	iTM2_TeX_src_specials_where_no_hbox: 1 or void,
+	iTM2_TeX_src_specials_where_no_parent: 1 or void,
+	iTM2_TeX_src_specials_where_no_par: 1 or void,
+	iTM2_TeX_src_specials_where_no_math: 1 or void,
+	iTM2_TeX_src_specials_where_no_vbox: 1 or void,
+	iTM2_TeX_USE_output_comment: 1 or void,
 	iTM2_TeX_output_comment:
-	iTM2_TeX_USE_translate_file: 1 or 0,
+	iTM2_TeX_USE_translate_file: 1 or void,
 	iTM2_TeX_translate_file := TCXNAME, use the TCX file TCXNAME
-	iTM2_TeX_PARSE_translate_file: 1 or 0,
-	iTM2_TeX_recorder: 1 or 0, enable filename recorder
-	iTM2_TeX_file_line_error: 1 or 0, print file:line:error style messages
-	iTM2_TeX_halt_on_error: 1 or 0,
+	iTM2_TeX_PARSE_translate_file: 1 or void,
+	iTM2_TeX_recorder: 1 or void, enable filename recorder
+	iTM2_TeX_file_line_error: 1 or void, print file:line:error style messages
+	iTM2_TeX_halt_on_error: 1 or void,
 	iTM2_TeX_interaction: batchmode/nonstopmode/scrollmode/errorstopmode, set interaction mode
 	iTM2_TeX_kpathsea_debug:
 	iTM2_TeX_MoreArgument: more arguments"
-echo "$iTM2_USAGE"
-exit 0
+	echo "$iTM2_USAGE"
 }
 "${iTM2_CMD_Notify}" comment "Welcome to $(basename "$0") version ${iTM2_TeX_Engine_Version}
 This is iTeXMac2 built in script to wrap the tex engine
-© 2005 jlaurens@users.sourceforge.net"
-if [ "${iTM2_Debug:-0}" != "0" ]
+© 2006 jlaurens@users.sourceforge.net"
+if [ ${#iTM2_Debug} -gt 0 ]
 then
 	"${iTM2_CMD_Notify}" start comment
 	"${iTM2_CMD_Notify}" echo "The $0 specific environment is:"
@@ -62,6 +63,7 @@ then
 	done
 	"${iTM2_CMD_Notify}" stop comment
 fi
+# the engine part
 
 iTM2_TeX_Engine="tex"
 iTM2_TeX_EnginePath="$(which "${iTM2_TeX_Engine}")"
@@ -69,33 +71,9 @@ if ! [ -x "${iTM2_TeX_EnginePath}" ]
 then
 	"${iTM2_CMD_Notify}" error "Unknown command ${iTM2_TeX_Engine}."
 	iTM2TeXEngineUsage
+	exit 1
 fi
-EXTENSION="$(basename ${TWSMaster})"
-EXTENSION="${EXTENSION##*.}"
-if [ ${#EXTENSION} -ne 0 ]
-then
-	EXTENSION="$(echo "${EXTENSION}" | tr 'TEX' 'tex')"
-	if [ "${EXTENSION}" != "tex" ]
-	then
-		TWSMaster="${TWSMaster%.*}.tex"
-	fi
-fi
-if ! [ -r "${TWSMaster}" ]
-then
-	"$iTM2_CMD_Notify" error "No readable file at ${TWSMaster} (in $(pwd))."
-	iTM2TeXEngineUsage
-fi
-"${iTM2_CMD_Notify}" comment "TWSMaster is: ${TWSMaster}"
-TARGET_DIRECTORY="$(dirname "${TWSMaster}")"
-TARGET="$(basename "${TWSMaster}")"
 iTM2_TeX_Arguments=""
-if [ "${iTM2_TeX_USE_jobname:-0}" != "0" ] && [ ${#iTM2_TeX_jobname} -ne 0 ]
-then
-	iTM2_TeX_Arguments="${iTM2_TeX_Arguments} -jobname \"${iTM2_TeX_jobname}\""
-	OUTPUT="${iTM2_TeX_jobname}"
-else
-	OUTPUT="${TARGET%.*}"
-fi
 if [ "${iTM2_TeX_ini:-0}" != "0" ]
 then
 	iTM2_TeX_Arguments="-ini"
@@ -174,7 +152,7 @@ if [ "${iTM2_TeX_kpathsea_debug:-0}" != "0" ]
 then
 	"${iTM2_CMD_Notify}" error "-kpathsea-debug no yet supported"
 fi
-if [ ${#iTM2_TeX_interaction} -gt 0 ]
+if [ "${iTM2_TeX_interaction:-0}" != "0" ]
 then
 	iTM2_TeX_Arguments="${iTM2_TeX_Arguments} -interaction ${iTM2_TeX_interaction}"
 fi
@@ -256,13 +234,98 @@ then
 		iTM2_TeX_Arguments="${iTM2_TeX_Arguments} -src-specials"
 	fi
 fi
-pushd "${TARGET_DIRECTORY}"
-"${iTM2_CMD_Notify}" comment "Performing  ${iTM2_TeX_EnginePath} ${iTM2_TeX_Arguments} \"${TARGET}\""
-"${iTM2_TeX_EnginePath}" ${iTM2_TeX_Arguments} "${TARGET}"
-popd
-iTM2_Command_Compile --master "${PWD}/${OUTPUT%.*}" --switch dvi
-if [ "${iTM2_Debug:-0}" != "0" ]
+# the file name part
+EXTENSION="$(basename ${TWSMaster})"
+EXTENSION="${EXTENSION##*.}"
+if [ ${#EXTENSION} -ne 0 ]
 then
-	"${iTM2_CMD_Notify}" error "$0 complete."
+	EXTENSION="$(echo "${EXTENSION}" | tr [:upper:] [:lower:])"
+	if [ "${EXTENSION}" != "tex" ] && [ "${EXTENSION}" != "dtx" ] && [ "${EXTENSION}" != "ins" ] && [ "${EXTENSION}" != "ltx" ]
+	then
+		TWSMaster="${TWSMaster%.*}.tex"
+	fi
 fi
+if ! [ -r "${TWSMaster}" ]
+then
+	"$iTM2_CMD_Notify" error "No readable file at ${TWSMaster} (in $(pwd))."
+	iTM2TeXEngineUsage
+	exit 2
+fi
+TWSMasterBase="$(basename "${TWSMaster}")"
+if [ "${iTM2_TeX_USE_jobname:-0}" != "0" ] && [ ${#iTM2_TeX_jobname} -ne 0 ]
+then
+	iTM2_TeX_Arguments="${iTM2_TeX_Arguments} -jobname \"${iTM2_TeX_jobname}\""
+	OUTPUT="${iTM2_TeX_jobname}"
+else
+	OUTPUT="${TWSMasterBase%.*}"
+fi
+# working directory?
+if [ ${#TWSProject} -gt 0 ]
+then
+	iTM2_PWD="$(dirname "${TWSProject}")"
+	iTM2_PWD_Real="${iTM2_PWD##*Projects.put_aside}"
+	iTM2_PWD_Real="${iTM2_PWD_Real%/*.texd*}"
+	if [ ${#iTM2_PWD_Real} -lt ${#iTM2_PWD} ]
+	then
+		if [ ${#TEXINPUTS} -gt 0 ]
+		then
+			export TEXINPUTS=".:${iTM2_PWD_Real}:${TEXINPUTS}:"
+		else
+			export TEXINPUTS=".:${iTM2_PWD_Real}:"
+		fi
+		if [ ${#iTM2_PWD} -gt 0 ] && ! [ -r "${iTM2_PWD}/${TWSMasterBase}" ]
+		then
+			ln -sf "{TWSMaster}" "${iTM2_PWD}"
+		fi
+	fi
+else
+	iTM2_PWD="$(dirname "${TWSMaster}")"
+	iTM2_PWD_Real="${iTM2_PWD}"
+fi
+pushd "${iTM2_PWD}"
+"${iTM2_CMD_Notify}" comment "Performing  ${iTM2_TeX_EnginePath} ${iTM2_TeX_Arguments} \"${TARGET}\""
+"${iTM2_TeX_EnginePath}" ${iTM2_TeX_Arguments} "${TWSMasterBase}"
+iTM2_Status="$?"
+if [ "${iTM2_Status}" != "0" ]
+then
+	popd
+	"$iTM2_CMD_Notify" error "$0 FAILED(${iTM2_Status})."
+	exit ${iTM2_Status}
+fi
+iTM2_Command_Compile --master "${iTM2_PWD}/${OUTPUT%.*}" --switch dvi
+iTM2_Status="$?"
+if [ "${iTM2ExportOutput:-0}" != "0" ]
+then
+	OUTPUT="${OUTPUT%.*}.ps"
+	if [ -s "${OUTPUT}" ]
+	then	
+		if [ ${#iTM2_PWD_Real} -lt ${#iTM2_PWD} ] && [ -w "${iTM2_PWD_Real}" ]
+		then
+			mv -f "${OUTPUT}" "${iTM2_PWD_Real}"
+		fi
+	else
+		"${iTM2_TemporaryDirectory}/bin/iTeXMac2" markerror -file "${iTM2_PWD_Real}/${OUTPUT}" -project "${TWSProject}"
+	fi
+fi
+OUTPUT="${OUTPUT%.*}.pdf"
+if [ -s "${OUTPUT}" ]
+then	
+	if [ ${#iTM2_PWD_Real} -lt ${#iTM2_PWD} ] && [ -w "${iTM2_PWD_Real}" ]
+	then
+		mv -f "${OUTPUT}" "${iTM2_PWD_Real}"
+	fi
+	"${iTM2_TemporaryDirectory}/bin/iTeXMac2" update -file "${iTM2_PWD_Real}/${OUTPUT}" -project "${TWSProject}"
+else
+	"${iTM2_TemporaryDirectory}/bin/iTeXMac2" markerror -file "${iTM2_PWD_Real}/${OUTPUT}" -project "${TWSProject}"
+fi
+if [ "${iTM2_Status}" != "0" ]
+then
+	"$iTM2_CMD_Notify" error "$0 FAILED(${iTM2_Status})."
+	popd
+	exit ${iTM2_Status}
+elif [ ${#iTM2_Debug} -gt 0 ]
+then
+	"${iTM2_CMD_Notify}" comment "$0 complete."
+fi
+popd
 exit
diff --git a/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/TeX/iTM2_Engine_XeTeX b/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/TeX/iTM2_Engine_XeTeX
--- a/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/TeX/iTM2_Engine_XeTeX
+++ b/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/TeX/iTM2_Engine_XeTeX
@@ -1,57 +1,58 @@
 #!/bin/sh -f
 # this is iTM2_Engine_XeTeX for iTeXMac2 2.0
-# © 2004 jlaurens@users.sourceforge.net
+# © 2006 jlaurens@users.sourceforge.net
 # This is a XeTeX 3.14159-2.1-0.88 (Web2C 7.5.2) wrapper
 iTM2_XeTeX_Engine_Version=1.0
 iTM2TeXEngineUsage()
 {
-iTM2_USAGE="Welcome to `basename "$0"` version ${iTM2_XeTeX_Engine_Version}
+iTM2_USAGE="Welcome to $(basename "$0") version ${iTM2_XeTeX_Engine_Version}
 This is iTeXMac2 built in script to wrap the XeTeX engine
-(`which "$0"`)
-© 2004 jlaurens@users.sourceforge.net
-Usage: `basename "$0"` with environment variables
-	TWSMaster: the main input file
-	iTM2_USE_output_directory: 1 or 0 (common)
+($(which xetex))
+© 2006 jlaurens@users.sourceforge.net
+Usage: $(basename "$0") with environment variables
+	TWSMaster: the main input file (actually \"${TWSMaster}\")
+	TWSProject: the project file, if any, full path, unused
+	TWSWrapper: the wrapper file, if any, full path, unused
+	iTM2_USE_output_directory: 1 or void (common)
 	iTM2_output_directory: the common output directory
-	iTM2_XeTeX_ini: 1 or 0, be initex, for dumping formats
-	iTM2_XeTeX_mltex: 1 or 0, enable MLTeX extensions such as \charsubdef
-	iTM2_XeTeX_enc: 1 or 0,
+	iTM2_XeTeX_ini: 1 or void, be initex, for dumping formats
+	iTM2_XeTeX_mltex: 1 or void, enable MLTeX extensions such as \charsubdef
+	iTM2_XeTeX_enc: 1 or void,
 	iTM2_XeTeX_MoreArgument:
-	iTM2_XeTeX_mktex: 1 or 0,
-	iTM2_XeTeX_USE_output_directory: 1 or 0
+	iTM2_XeTeX_mktex: 1 or void,
+	iTM2_XeTeX_USE_output_directory: 1 or void
 	iTM2_XeTeX_output_directory:
 	iTM2_XeTeX_fmt: = FMTNAME, use the value instead of program name or a %& line
-	iTM2_XeTeX_parse_first_line: 1 or 0, parse of the first line of the input file
-	iTM2_XeTeX_USE_progname: 1 or 0,
+	iTM2_XeTeX_parse_first_line: 1 or void, parse of the first line of the input file
+	iTM2_XeTeX_USE_progname: 1 or void,
 	iTM2_XeTeX_progname: = STRING, set program (and fmt) name to STRING
-	iTM2_XeTeX_USE_jobname: 1 or 0,
+	iTM2_XeTeX_USE_jobname: 1 or void,
 	iTM2_XeTeX_jobname: = STRING, set the job name to STRING
-	iTM2_XeTeX_shell_escape: 1 or 0, enable \write18{SHELL COMMAND}
-	iTM2_XeTeX_src_specials: 1 or 0, insert source specials into the DVI file
-	iTM2_XeTeX_src_specials_where_no_cr: 1 or 0,
-	iTM2_XeTeX_src_specials_where_no_display: 1 or 0,
-	iTM2_XeTeX_src_specials_where_no_hbox: 1 or 0,
-	iTM2_XeTeX_src_specials_where_no_parent: 1 or 0,
-	iTM2_XeTeX_src_specials_where_no_par: 1 or 0,
-	iTM2_XeTeX_src_specials_where_no_math: 1 or 0,
-	iTM2_XeTeX_src_specials_where_no_vbox: 1 or 0,
-	iTM2_XeTeX_USE_output_comment: 1 or 0,
+	iTM2_XeTeX_shell_escape: 1 or void, enable \write18{SHELL COMMAND}
+	iTM2_XeTeX_src_specials: 1 or void, insert source specials into the DVI file
+	iTM2_XeTeX_src_specials_where_no_cr: 1 or void,
+	iTM2_XeTeX_src_specials_where_no_display: 1 or void,
+	iTM2_XeTeX_src_specials_where_no_hbox: 1 or void,
+	iTM2_XeTeX_src_specials_where_no_parent: 1 or void,
+	iTM2_XeTeX_src_specials_where_no_par: 1 or void,
+	iTM2_XeTeX_src_specials_where_no_math: 1 or void,
+	iTM2_XeTeX_src_specials_where_no_vbox: 1 or void,
+	iTM2_XeTeX_USE_output_comment: 1 or void,
 	iTM2_XeTeX_output_comment:
-	iTM2_XeTeX_USE_translate_file: 1 or 0,
+	iTM2_XeTeX_USE_translate_file: 1 or void,
 	iTM2_XeTeX_translate_file := TCXNAME, use the TCX file TCXNAME
-	iTM2_XeTeX_PARSE_translate_file: 1 or 0,
-	iTM2_XeTeX_recorder: 1 or 0, enable filename recorder
-	iTM2_XeTeX_file_line_error: 1 or 0, print file:line:error style messages
-	iTM2_XeTeX_halt_on_error: 1 or 0,
+	iTM2_XeTeX_PARSE_translate_file: 1 or void,
+	iTM2_XeTeX_recorder: 1 or void, enable filename recorder
+	iTM2_XeTeX_file_line_error: 1 or void, print file:line:error style messages
+	iTM2_XeTeX_halt_on_error: 1 or void,
 	iTM2_XeTeX_interaction: batchmode/nonstopmode/scrollmode/errorstopmode, set interaction mode
 	iTM2_XeTeX_kpathsea_debug:
 	iTM2_XeTeX_MoreArgument: more arguments"
 "$iTM2_CMD_Notify" echo "$iTM2_USAGE"
-exit 0
 }
-"$iTM2_CMD_Notify" echo "Welcome to `basename "$0"` version ${iTM2_XeTeX_Engine_Version}
+"$iTM2_CMD_Notify" comment "Welcome to $(basename "$0") version ${iTM2_XeTeX_Engine_Version}
 This is iTeXMac2 built in script to wrap the XeTeX engine
-© 2005 jlaurens@users.sourceforge.net"
+© 2006 jlaurens@users.sourceforge.net"
 if [ "${iTM2_Debug:-0}" != "0" ]
 then
 	"$iTM2_CMD_Notify" start comment
@@ -64,28 +65,13 @@ then
 fi
 
 iTM2_XeTeX_Engine="xetex"
-iTM2_XeTeX_EnginePath="`which "${iTM2_XeTeX_Engine}"`"
+iTM2_XeTeX_EnginePath="$(which "${iTM2_XeTeX_Engine}")"
 if ! [ -x "${iTM2_XeTeX_EnginePath}" ]
 then
 	"$iTM2_CMD_Notify" error "Unknown command ${iTM2_XeTeX_Engine}."
 	iTM2TeXEngineUsage
+	exit 1
 fi
-EXTENSION="$(basename ${TWSMaster})"
-EXTENSION="${EXTENSION##*.}"
-if [ ${#EXTENSION} -ne 0 ]
-then
-	EXTENSION="$(echo "${EXTENSION}" | tr 'TEX' 'tex')"
-	if [ "${EXTENSION}" != "tex" ]
-	then
-		TWSMaster="${TWSMaster%.*}.tex"
-	fi
-fi
-if ! [ -r "${TWSMaster}" ]
-then
-	"$iTM2_CMD_Notify" error "No readable file at ${TWSMaster} (in $(pwd))."
-	iTM2TeXEngineUsage
-fi
-"$iTM2_CMD_Notify" comment "TWSMaster is: ${TWSMaster}"
 iTM2_XeTeX_Arguments=""
 if [ "${iTM2_XeTeX_ini:-0}" != "0" ]
 then
@@ -128,7 +114,7 @@ then
 		iTM2_XeTeX_Arguments="${iTM2_XeTeX_Arguments} -progname \"${iTM2_XeTeX_progname}\""
 	fi
 else
-	iTM2_XeTeX_fmt="`echo ${iTM2_XeTeX_fmt} | tr [:upper:] [:lower:]`"
+	iTM2_XeTeX_fmt="$(echo ${iTM2_XeTeX_fmt} | tr [:upper:] [:lower:])"
 	if [ "${iTM2_XeTeX_USE_progname:-0}" != "0" ] && [ ${#iTM2_XeTeX_progname} -ne 0 ]
 	then
 		iTM2_XeTeX_Arguments="${iTM2_XeTeX_Arguments} -progname \"${iTM2_XeTeX_progname}\""
@@ -183,39 +169,84 @@ if [ "${iTM2_XeTeX_USE_MoreArgument:-0}" != "0" ] && [ ${#iTM2_XeTeX_MoreArgumen
 then
 	iTM2_XeTeX_Arguments="${iTM2_XeTeX_Arguments} \"${iTM2_XeTeX_MoreArgument}\""
 fi
-TARGET_DIRECTORY="$(dirname "${TWSMaster}")"
-pushd "${TARGET_DIRECTORY}"
-TARGET="$(basename "${TWSMaster}")"
-"$iTM2_CMD_Notify" comment "Performing  ${iTM2_XeTeX_EnginePath} ${iTM2_XeTeX_Arguments} \"${TARGET}\""
-${iTM2_XeTeX_EnginePath} ${iTM2_XeTeX_Arguments} "${TARGET}"
-popd
-if [ "${iTM2_Debug:-0}" != "0" ]
+# the file name part
+TWSMasterBase="$(basename "${TWSMaster}")"
+EXTENSION="${TWSMasterBase##*.}"
+if [ ${#EXTENSION} -ne 0 ]
+then
+	EXTENSION="$(echo "${EXTENSION}" | tr [:upper:] [:lower:])"
+	if [ "${EXTENSION}" != "tex" ] && [ "${EXTENSION}" != "dtx" ] && [ "${EXTENSION}" != "ins" ] && [ "${EXTENSION}" != "ltx" ]
+	then
+		TWSMaster="${TWSMaster%.*}.tex"
+	fi
+fi
+if ! [ -r "${TWSMaster}" ]
+then
+	"$iTM2_CMD_Notify" error "No readable file at ${TWSMaster} (in $(pwd))."
+	iTM2TeXEngineUsage
+	exit 2
+fi
+"$iTM2_CMD_Notify" comment "TWSMaster is: ${TWSMaster}"
+if [ "${iTM2_XeTeX_USE_jobname:-0}" != "0" ] && [ ${#iTM2_XeTeX_jobname} -ne 0 ]
+then
+	iTM2_XeTeX_Arguments="${iTM2_XeTeX_Arguments} -jobname \"${iTM2_XeTeX_jobname}\""
+	OUTPUT="${iTM2_XeTeX_jobname}"
+else
+	OUTPUT="${TWSMasterBase%.*}"
+fi
+# working directory?
+if [ ${#TWSProject} -gt 0 ]
+then
+	iTM2_PWD="$(dirname "${TWSProject}")"
+	iTM2_PWD_Real="${iTM2_PWD##*Projects.put_aside}"
+	iTM2_PWD_Real="${iTM2_PWD_Real%/*.texd*}"
+	if [ ${#iTM2_PWD_Real} -lt ${#iTM2_PWD} ]
+	then
+		if [ ${#TEXINPUTS} -gt 0 ]
+		then
+			export TEXINPUTS=".:${iTM2_PWD_Real}:${TEXINPUTS}:"
+		else
+			export TEXINPUTS=".:${iTM2_PWD_Real}:"
+		fi
+		if [ ${#iTM2_PWD} -gt 0 ] && ! [ -r "${iTM2_PWD}/${TWSMasterBase}" ]
+		then
+			ln -sf "{TWSMaster}" "${iTM2_PWD}"
+		fi
+	fi
+else
+	iTM2_PWD="$(dirname "${TWSMaster}")"
+	iTM2_PWD_Real="${iTM2_PWD}"
+fi
+pushd "${iTM2_PWD}"
+"$iTM2_CMD_Notify" comment "Performing  ${iTM2_XeTeX_EnginePath} ${iTM2_XeTeX_Arguments} \"${TWSMasterBase}\""
+"${iTM2_XeTeX_EnginePath}" ${iTM2_XeTeX_Arguments} "${TWSMasterBase}"
+iTM2_Status="$?"
+if [ "${iTM2_Status}" != "0" ]
+then
+#	popd// bug in xetex
+	"$iTM2_CMD_Notify" error "$0 FAILED(${iTM2_Status})."
+	"$iTM2_CMD_Notify" error "WARNING: this might be a xetex bug, if there is no error"
+#	exit ${iTM2_Status}
+fi
+OUTPUT="${OUTPUT%.*}.pdf"
+"$iTM2_CMD_Notify" comment "OUTPUT: ${OUTPUT}"
+if [ -s "${OUTPUT}" ]
+then	
+	if [ ${#iTM2_PWD_Real} -lt ${#iTM2_PWD} ] && [ -w "${iTM2_PWD_Real}" ]
+	then
+		mv -f "${OUTPUT}" "${iTM2_PWD_Real}"
+"$iTM2_CMD_Notify" comment "! moved 1 OUTPUT: ${OUTPUT}"
+	fi
+"$iTM2_CMD_Notify" comment "! moved 2 OUTPUT: ${OUTPUT}"
+	"${iTM2_TemporaryDirectory}/bin/iTeXMac2" update -file "${iTM2_PWD_Real}/${OUTPUT}" -project "${TWSProject}"
+else
+"$iTM2_CMD_Notify" comment "! moved 3 OUTPUT: ${OUTPUT}"
+	"${iTM2_TemporaryDirectory}/bin/iTeXMac2" markerror -file "${iTM2_PWD_Real}/${OUTPUT}" -project "${TWSProject}"
+fi
+if [ ${#iTM2_Debug} -gt 0 ]
 then
 	"$iTM2_CMD_Notify" comment "$0 complete."
 fi
-"${iTM2_TemporaryDirectory}/bin/iTeXMac2" update -file "${PWD}/${TWSMaster%.*}.pdf" -project "${TWSProjectDirectory}/${TWSProjectName}"
-exit
+popd
+exit ${iTM2_Status}
 
--file-line-error-style   print file:line:error style messages
--ini                     be xeinitex, for dumping formats; this is implicitly
-                          true if the program name is `xeinitex'
--interaction=STRING      set interaction mode (STRING=batchmode/nonstopmode/
-                          scrollmode/errorstopmode)
--jobname=STRING          set the job name to STRING
--kpathsea-debug=NUMBER   set path searching debugging flags according to
-                          the bits of NUMBER
-[-no]-mktex=FMT          disable/enable mktexFMT generation (FMT=tex/tfm)
--output-comment=STRING   use STRING for output file comment instead of date
--papersize=STRING        use STRING for PDF media size instead of default
--parse-first-line        parse of the first line of the input file
-[-no]-pdf                disable/enable automatic conversion of XDV to PDF
--progname=STRING         set program (and fmt) name to STRING
--recorder                enable filename recorder
--shell-escape            enable \write18{SHELL COMMAND}
--src-specials            insert source specials into the output file
--src-specials=WHERE      insert source specials in certain places of
-                          the output file. WHERE is a comma-separated value
-                          list: cr display hbox math par parent vbox
--help                    display this help and exit
--version                 output version information and exit
--fmt=FMTNAME            use FMTNAME instead of program name or a %& line
diff --git a/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/dvips/iTM2_Engine_dvips b/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/dvips/iTM2_Engine_dvips
--- a/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/dvips/iTM2_Engine_dvips
+++ b/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/dvips/iTM2_Engine_dvips
@@ -1,15 +1,15 @@
 #!/bin/sh -f
 # this is iTM2_dvips wrapper
-# © 2005 jlaurens@users.sourceforge.net
+# © 2006 jlaurens@users.sourceforge.net
 iTM2_dvips_Engine_Version=1.0
 iTM2DVIPSMEngineUsage()
 {
-iTM2_USAGE="Welcome to `basename "$0"` version ${iTM2_dvips_Engine_Version}
+iTM2_USAGE="Welcome to $(basename "$0") version ${iTM2_dvips_Engine_Version}
 This is iTeXMac2 built in script to wrap the dvips engine
-(`which "$0"`)
-© 2005 jlaurens@users.sourceforge.net
-Usage: `basename "$0"` with environment variables
-	TWSMaster: the main input file
+($(which dvips))
+© 2006 jlaurens@users.sourceforge.net
+Usage: $(basename "$0") with environment variables
+	TWSMaster: the main input file (actually \"${TWSMaster}\")
 	iTM2_dvips_multiple_copies: 1 or 0,
 	iTM2_dvips_num_copies: NUM (1 is default),
 	iTM2_dvips_collated_copies: 1 or 0,
@@ -71,11 +71,10 @@ Usage: `basename "$0"` with environment variables
 	iTM2_dvips_USE_more_arguments: 1 or 0,
 	iTM2_dvips_more_arguments: \"\""
 echo "$iTM2_USAGE"
-exit 0
 }
-"$iTM2_CMD_Notify" comment "Welcome to `basename "$0"` version ${iTM2_dvips_Engine_Version}
+"$iTM2_CMD_Notify" comment "Welcome to $(basename "$0") version ${iTM2_dvips_Engine_Version}
 This is iTeXMac2 built in script to wrap the dvips engine
-© 2005 jlaurens@users.sourceforge.net"
+© 2006 jlaurens@users.sourceforge.net"
 if [ "${iTM2_Debug:-0}" != "0" ]
 then
 	"$iTM2_CMD_Notify" start comment
@@ -87,40 +86,40 @@ then
 	"$iTM2_CMD_Notify" stop comment
 fi
 iTM2_dvips_Engine="dvips"
-iTM2_dvips_EnginePath="`which "${iTM2_dvips_Engine}"`"
+iTM2_dvips_EnginePath="$(which "${iTM2_dvips_Engine}")"
 if ! [ -x "${iTM2_dvips_EnginePath}" ]
 then
 	"$iTM2_CMD_Notify" error "Unknown command ${iTM2_dvips_Engine}."
 	iTM2DVIPDFMEngineUsage
 fi
+pushd "$(dirname "${TWSMaster}")"
+iTM2_PWD="$(pwd)"
+iTM2_INPUT="$(basename "${TWSMaster}")"
 if ! [ -r "${TWSMaster}" ]
 then
-    TWSMaster="${TWSMaster}.dvi"
-    if ! [ -r "${TWSMaster}" ]
+    iTM2_INPUT="${iTM2_INPUT%.*}.dvi"
+    if ! [ -r "${iTM2_INPUT}" ]
     then
-        "$iTM2_CMD_Notify" error "No readable file at ${TWSMaster}."
+        "$iTM2_CMD_Notify" error "No readable file at ${iTM2_PWD}/${iTM2_INPUT}."
         iTM2DVIPSMEngineUsage
+		popd
+		exit 1
     fi
 fi
-"$iTM2_CMD_Notify" comment "TWSMaster is: ${TWSMaster}"
-pushd "$(dirname "${TWSMaster}")"
-INPUT_DIRECTORY="${PWD}"
-popd
-INPUT="$(basename "${TWSMaster}")"
-iTM2_dvips_Arguments=""
 #output
 if [ "${iTM2_dvips_USE_output:-0}" != "0" ] && [ ${#iTM2_dvips_output} -gt 0 ]
 then
 	OUTPUT="${iTM2_dvips_output}"
 else
-    OUTPUT="${INPUT}"
+    OUTPUT="${iTM2_INPUT}"
 fi
 #if OUTPUT has a dvi extension, remove it
 EXTENSION="${OUTPUT##*.}"
-if [ "$(echo ${EXTENSION}|tr '[A-Z]' '[a-z]')" == "dvi" ]
+if [ "$(echo ${EXTENSION}|tr [:upper:] [:lower:])" == "dvi" ]
 then
     OUTPUT="${OUTPUT%.*}"
 fi
+iTM2_dvips_Arguments=""
 #copies
 if [ "${iTM2_dvips_multiple_copies:-0}" != "0" ] && [ ${iTM2_dvips_num_copies} -gt 0 ]
 then
@@ -203,7 +202,7 @@ then
 	iTM2_dvips_Arguments="${iTM2_dvips_Arguments} -t"
 fi
 #postscript
-#if OUTPUT dos not has a ps or an eps extension, add it
+#if OUTPUT does not have a ps or an eps extension, add it
 REQUIRED_EXTENSION="ps"
 case ${iTM2_dvips_generate_epsf} in
 	-1)
@@ -357,13 +356,23 @@ if [ "${iTM2_dvips_USE_more_arguments:-0}" != "0" ] && [ ${#iTM2_dvips_more_argu
 then
 	iTM2_dvips_Arguments="${iTM2_dvips_Arguments} ${iTM2_dvips_more_arguments}"
 fi
-pushd "${INPUT_DIRECTORY}"
-"$iTM2_CMD_Notify" comment "Performing  ${iTM2_dvips_EnginePath} ${iTM2_dvips_Arguments} \"${INPUT}\""
-${iTM2_dvips_EnginePath} ${iTM2_dvips_Arguments} "${INPUT}"
+"$iTM2_CMD_Notify" comment "Performing  ${iTM2_dvips_EnginePath} ${iTM2_dvips_Arguments} \"${iTM2_INPUT}\""
+"${iTM2_dvips_EnginePath}" ${iTM2_dvips_Arguments} "${iTM2_INPUT}"
+iTM2_Status="$?"
 popd
-echo "master is: ${INPUT_DIRECTORY}/${OUTPUT%.*}"
-iTM2_Command_Compile --master "${INPUT_DIRECTORY}/${OUTPUT%.*}" --switch ps
-if [ "${iTM2_Debug:-0}" != "0" ]
+if [ "${iTM2_Status}" != "0" ]
+then
+	"$iTM2_CMD_Notify" error "$0 FAILED(${iTM2_Status})."
+	exit ${iTM2_Status}
+fi
+echo "master is: ${iTM2_PWD}/${OUTPUT%.*}"
+iTM2_Command_Compile --master "${iTM2_PWD}/${OUTPUT%.*}" --switch ps
+iTM2_Status="$?"
+if [ "${iTM2_Status}" != "0" ]
+then
+	"$iTM2_CMD_Notify" error "$0 FAILED(${iTM2_Status})."
+	exit ${iTM2_Status}
+elif [ "${iTM2_Debug:-0}" != "0" ]
 then
 	"$iTM2_CMD_Notify" comment "$0 complete."
 fi
diff --git a/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/pstopdf/iTM2_Engine_pstopdf b/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/pstopdf/iTM2_Engine_pstopdf
--- a/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/pstopdf/iTM2_Engine_pstopdf
+++ b/itexmac2/trunk/iTM2TeXFoundation/iTM2TeXFoundationEngines/pstopdf/iTM2_Engine_pstopdf
@@ -6,18 +6,17 @@ iTM2DVIPDFMEngineUsage()
 {
 iTM2_USAGE="Welcome to `basename "$0"` version ${iTM2_pstopdf_Engine_Version}
 This is iTeXMac2 built in script to wrap the pstopdf engine
-(`which "$0"`)
-© 2005 jlaurens@users.sourceforge.net
-Usage: `basename "$0"` with environment variables
-	TWSMaster: the main input file
+($(which "$0"))
+© 2006 jlaurens@users.sourceforge.net
+Usage: $(basename "$0") with environment variables
+	TWSMaster: the main input file (actually \"${TWSMaster}\")
 	iTM2_pstopdf_use_output: 1 or 0,
 	iTM2_pstopdf_output: output file name,
 	iTM2_pstopdf_write_to_log: 1 or 0,
 	iTM2_pstopdf_progress_message: 1 or 0"
 echo "$iTM2_USAGE"
-exit 0
 }
-"$iTM2_CMD_Notify" comment "Welcome to `basename "$0"` version ${iTM2_pstopdf_Engine_Version}
+"$iTM2_CMD_Notify" comment "Welcome to $(basename "$0") version ${iTM2_pstopdf_Engine_Version}
 This is iTeXMac2 built in script to wrap the pstopdf engine
 © 2005 jlaurens@users.sourceforge.net"
 if [ "${iTM2_Debug:-0}" != "0" ]
@@ -36,6 +35,7 @@ if ! [ -x "${iTM2_pstopdf_EnginePath}" ]
 then
 	"$iTM2_CMD_Notify" error "Unknown command ${iTM2_pstopdf_Engine}."
 	iTM2DVIPDFMEngineUsage
+	exit 1
 fi
 "$iTM2_CMD_Notify" comment "TWSMaster is: ${TWSMaster}"
 pushd "$(dirname "${TWSMaster}")"
@@ -53,6 +53,7 @@ then
         then
             "$iTM2_CMD_Notify" error "No readable file at ${INPUT}."
             iTM2DVIPDFMEngineUsage
+			exit 2
         fi
     fi
 fi
@@ -71,17 +72,24 @@ then
     OUTPUT="${iTM2_pstopdf_output}"
 fi
 # add .pdf if necessary
-if [ "`echo ${OUTPUT##*.}|tr '[A-Z]' '[a-z]'`" != "pdf" ]
+if [ "$(echo ${OUTPUT##*.}|tr [:upper:] [:lower:])" != "pdf" ]
 then
     OUTPUT="${OUTPUT}.pdf"
 fi
 iTM2_pstopdf_Arguments="${iTM2_pstopdf_Arguments} -o ${OUTPUT}"
 "$iTM2_CMD_Notify" comment "Performing  ${iTM2_pstopdf_EnginePath} ${iTM2_pstopdf_Arguments} \"${INPUT}\""
-${iTM2_pstopdf_EnginePath} ${iTM2_pstopdf_Arguments} "${INPUT}"
+"${iTM2_pstopdf_EnginePath}" ${iTM2_pstopdf_Arguments} "${INPUT}"
+iTM2_Status="$?"
+if [ "${iTM2_Status}" != "0" ]
+then
+	popd
+	"$iTM2_CMD_Notify" error "$0 FAILED(${iTM2_Status})."
+	exit ${iTM2_Status}
+fi
 popd
 if [ "${iTM2_Debug:-0}" != "0" ]
 then
 	"$iTM2_CMD_Notify" comment "$0 complete."
 fi
-"${iTM2_TemporaryDirectory}/bin/iTeXMac2" update -file "${INPUT_DIRECTORY}/${OUTPUT}" -project "${TWSProjectDirectory}/${TWSProjectName}"
+"${iTM2_TemporaryDirectory}/bin/iTeXMac2" update -file "${INPUT_DIRECTORY}/${OUTPUT}" -project "${TWSProject}"
 exit 0
